#
# Set output directories for jni binaries to meaningful values
# By default output dirs are located under 'bin/UNKNOWN' for non-standard target platforms
#

IF(TARGET_BUILD_PLATFORM STREQUAL "jni-windows")
    SET(PX_ROOT_LIB_DIR "bin/jni-windows.x86_64" CACHE INTERNAL "Relative root of the lib output directory")
    SET(PX_ROOT_EXE_DIR "bin/jni-windows.x86_64" CACHE INTERNAL "Relative root dir of the exe output directory")

ELSEIF(TARGET_BUILD_PLATFORM STREQUAL "jni-linux")
    SET(PX_ROOT_LIB_DIR "bin/jni-linux.x86_64" CACHE INTERNAL "Relative root of the lib output directory")
    SET(PX_ROOT_EXE_DIR "bin/jni-linux.x86_64" CACHE INTERNAL "Relative root dir of the exe output directory")

ELSEIF(TARGET_BUILD_PLATFORM STREQUAL "jni-mac" AND PX_OUTPUT_ARCH STREQUAL "arm")
    SET(PX_ROOT_LIB_DIR "bin/jni-mac.aarch64" CACHE INTERNAL "Relative root of the lib output directory")
    SET(PX_ROOT_EXE_DIR "bin/jni-mac.aarch64" CACHE INTERNAL "Relative root dir of the exe output directory")

ELSEIF(TARGET_BUILD_PLATFORM STREQUAL "jni-mac")
    SET(PX_ROOT_LIB_DIR "bin/jni-mac.x86_64" CACHE INTERNAL "Relative root of the lib output directory")
    SET(PX_ROOT_EXE_DIR "bin/jni-mac.x86_64" CACHE INTERNAL "Relative root dir of the exe output directory")
ENDIF()

SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_DEBUG   "${PX_OUTPUT_LIB_DIR}/${PX_ROOT_LIB_DIR}/debug"   )
SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_PROFILE "${PX_OUTPUT_LIB_DIR}/${PX_ROOT_LIB_DIR}/profile" )
SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_CHECKED "${PX_OUTPUT_LIB_DIR}/${PX_ROOT_LIB_DIR}/checked" )
SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE "${PX_OUTPUT_LIB_DIR}/${PX_ROOT_LIB_DIR}/release" )

SET(CMAKE_LIBRARY_OUTPUT_DIRECTORY_DEBUG   "${PX_OUTPUT_LIB_DIR}/${PX_ROOT_LIB_DIR}/debug"   )
SET(CMAKE_LIBRARY_OUTPUT_DIRECTORY_PROFILE "${PX_OUTPUT_LIB_DIR}/${PX_ROOT_LIB_DIR}/profile" )
SET(CMAKE_LIBRARY_OUTPUT_DIRECTORY_CHECKED "${PX_OUTPUT_LIB_DIR}/${PX_ROOT_LIB_DIR}/checked" )
SET(CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE "${PX_OUTPUT_LIB_DIR}/${PX_ROOT_LIB_DIR}/release" )

SET(PX_EXE_OUTPUT_DIRECTORY_DEBUG 		"${PX_OUTPUT_BIN_DIR}/${PX_ROOT_EXE_DIR}/debug"	  CACHE INTERNAL "Directory to put debug exes in")
SET(PX_EXE_OUTPUT_DIRECTORY_PROFILE  	"${PX_OUTPUT_BIN_DIR}/${PX_ROOT_EXE_DIR}/profile" CACHE INTERNAL "Directory to put profile exes in")
SET(PX_EXE_OUTPUT_DIRECTORY_CHECKED 	"${PX_OUTPUT_BIN_DIR}/${PX_ROOT_EXE_DIR}/checked" CACHE INTERNAL "Directory to put checked exes in")
SET(PX_EXE_OUTPUT_DIRECTORY_RELEASE  	"${PX_OUTPUT_BIN_DIR}/${PX_ROOT_EXE_DIR}/release" CACHE INTERNAL "Directory to put release exes in")

SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG 	${CMAKE_ARCHIVE_OUTPUT_DIRECTORY_DEBUG}			)
SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY_PROFILE  ${CMAKE_ARCHIVE_OUTPUT_DIRECTORY_PROFILE}		)
SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY_CHECKED 	${CMAKE_ARCHIVE_OUTPUT_DIRECTORY_CHECKED}  		)
SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE  ${CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE}		)